apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  replicas: 2
  template:
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: goserver
          image: flf2ko/goserver:v1.2.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PHASE
              value: dev
          ports:
            - name: api-port
              containerPort: 8999
              protocol: TCP
            - name: profile-api
              containerPort: 10201
              protocol: TCP
